### ISSUE TITLE
UnescapedEntity support for @snippet javadoc tag

### ISSUE THREAD

**Issue by ben-manes** [google/error-prone#4914]
The `{@snippet : ...}` is the preferred replacement for `<pre>{@code ...}</pre>` code blocks. When mirroring the [guava change](https://github.com/google/guava/commit/157b3f7e5ebff7beb6d32d511b8693d759be7d66) I received the following warnings:

```
/Users/ben/projects/caffeine/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java:73: warning: [UnescapedEntity] This looks like a type with type parameters. The < and > characters here will be interpreted as HTML, which can be avoided by wrapping it in a {@code } tag.
 *   LoadingCache<Key, Graph> graphs = Caffeine.newBuilder()
     ^
    (see https://errorprone.info/bugpattern/UnescapedEntity)
  Did you mean '*   {@code LoadingCache<Key, Graph>} graphs = Caffeine.newBuilder()'?
```

for the code,
```java
 * {@snippet :
 *   LoadingCache<Key, Graph> graphs = Caffeine.newBuilder()
 *       .maximumSize(10_000)
 *       .expireAfterWrite(Duration.ofMinutes(10))
 *       .removalListener((Key key, Graph graph, RemovalCause cause) ->
 *           System.out.printf("Key %s was removed (%s)%n", key, cause))
 *       .build(key -> createExpensiveGraph(key));
 * }
```

and the JavaDoc comes out perfect

<img width="1275" alt="Image" src="https://github.com/user-attachments/assets/e0be7886-9dc6-4e1d-a47f-4dc53d5f14b2" />

**Comment by graememorgan** [comment]
Urk. We have support for this, but it's being stripped from the OSS release, given it's pegged to Java 17, and `@snippet` is a Java 18 feature.

Apologies for the noise; Liam filed #4867 the other day to track bumping us to 21 externally as well as internally.

**Comment by ben-manes** [comment]
Oh I [generate](https://github.com/ben-manes/caffeine/blob/d49327cc417d9088a19143394d6c4fb292186c49/gradle/plugins/src/main/kotlin/lifecycle/java-library.caffeine.gradle.kts#L90) Javadoc using the later version than the source code. It works fine since the html rendering is independent and can target a release for the links, but maybe that is not strictly kosher.

**Comment by tbroyer** [comment]
Isn't just a case of adding `snippet` to `PRE_TAGS` in this case?

https://github.com/google/error-prone/blob/81faa5aed9cc3ddb38ff97d2ef497e44cd289c0d/core/src/main/java/com/google/errorprone/bugpatterns/javadoc/UnescapedEntity.java#L76

**Comment by graememorgan** [comment]
> Isn't just a case of adding snippet to PRE_TAGS in this case?

`@snippet` is not an HTML tag.

> Oh I generate Javadoc using the later version than the source code. It works fine since the html rendering is independent and can target a release for the links, but maybe that is not strictly kosher.

Sorry, what I meant is that the open source ErrorProne release only contains features up to 17, while `@snippet` is 18, so we don't yet have the "feature" of ignoring `@snippet` in the OSS release.

**Comment by tbroyer** [comment]
> > Isn't just a case of adding snippet to PRE_TAGS in this case?
> 
> `@snippet` is not an HTML tag.

silly me 🤦

**Comment by ben-manes** [comment]
Closing as I don't see it anymore and presumably it was resolved with [v2.43.0](https://github.com/google/error-prone/releases/tag/v2.43.0).

**Comment by Stephan202** [comment]
@ben-manes I wonder whether you stopped seeing this issue for other reasons, as I suspect it's not solved. With [these changes](https://github.com/PicnicSupermarket/error-prone-support/commit/b6901d5e53e105d1e435fcd8c1ddd3e424812edb):
```diff
diff --git a/error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreTypes.java b/error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreTypes.java
index 8291f542..cfb9bfa0 100644
--- a/error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreTypes.java
+++ b/error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreTypes.java
@@ -19,13 +19,13 @@ import java.util.function.BiFunction;
  *
  * <p>These methods are meant to be statically imported. Example usage:
  *
- * <pre>{@code
+ * {@snippet :
  * Supplier<Type> type =
  *     VisitorState.memoize(
  *         generic(
  *             type("reactor.core.publisher.Flux"),
  *             subOf(generic(type("org.reactivestreams.Publisher"), unbound()))));
- * }</pre>
+ * }
  *
  * This statement produces a memoized supplier of the type {@code Flux<? extends Publisher<?>>}.
  */
```

I see:
```
[WARNING] /path/to/error-prone-support/error-prone-utils/src/main/java/tech/picnic/errorprone/utils/MoreTypes.java:[23,4] [UnescapedEntity] This looks like a type with type parameters. The < and > characters here will be interpreted as HTML, which can be avoided by wrapping it in a {@code } tag.
    (see https://errorprone.info/bugpattern/UnescapedEntity)
  Did you mean '* {@code Supplier<Type>} type ='?
```

Shall we reopen this issue? @graememorgan while #4867 is still open, Error Prone does now target JDK 21 as a baseline. So would it be possible to mirror the internal improvements you mentioned to the open source code base? 🙏

**Comment by cushon** [comment]
> would it be possible to mirror the internal improvements you mentioned to the open source code base

I'll prepare a change for that
